real_estate_project/real_estate_site/urls.py
from django.contrib import admin
from django.urls import path

from pages.views import home_view
from search.views import search_view
from interestapp.views import interest_view, bank_view, tax_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home_view, name="home"),
    path("laisuat/", interest_view),
    path("tracuu/", bank_view),
    path("search/", search_view),
    path("thue/", tax_view),
]

real_estate_project/interestapp/models.py
from django.db import models

class Bank(models.Model):
    ten_ngan_hang = models.CharField('Tên ngân hàng', max_length=120)
    lai_suat = models.DecimalField('Lãi suất mua nhà % (năm) ', decimal_places=2, max_digits=15)

    def __str__(self):
        return f"{self.ten_ngan_hang}"

    class Meta:
        ordering = ("ten_ngan_hang", "lai_suat")

real_estate_project/interestapp/forms.py
from django import forms
from .models import Bank

class InterestForm(forms.Form):
    # CHOICE
    TYPE_CHOICES = (
        ("1", "Dư nợ giảm dần (kỳ khoản giảm dần)"),
        ("2", "Dư nợ giảm dần (kỳ khoản cố định)"),
    )
    so_tien_vay = forms.DecimalField(label="Số tiền vay (VND)", max_digits=15, localize=True)
    ky_han = forms.IntegerField(label="Thời gian vay (tháng)")
    lai_suat = forms.DecimalField(decimal_places=2, label="Lãi suất % (năm)")
    loai_hinh = forms.ChoiceField(choices=TYPE_CHOICES, label="Loại hình")

    # Updating class for each form
    lai_suat.widget.attrs.update({'class': 'myclass'})
    ky_han.widget.attrs.update({'class': 'myclass'})
    so_tien_vay.widget.attrs.update({'class': 'myclass'})
    loai_hinh.widget.attrs.update({'class': 'loaihinhclass'})

class BankForm(forms.Form):

    initial = tuple(['Không có', 'Chọn ngân hàng'])
    CHOICE = tuple(Bank.objects.values_list('lai_suat','ten_ngan_hang'))
    CHOICES = (initial,) + CHOICE

    ten_ngan_hang = forms.ChoiceField(choices=CHOICES, required=False,
                                           label="Ngân hàng",
    )
    ten_ngan_hang.widget.attrs.update({'class': 'loaihinhclass', 'id': "mySelect",
                                       'onchange': 'show_laisuat()'
                                    })


class TaxForm(forms.Form):
    gia_chuyen_nhuong = forms.DecimalField(label="Giá chuyển nhượng", max_digits=15, localize=True)

    gia_chuyen_nhuong.widget.attrs.update({'class': 'myclass'})

real_estate_project/interestapp/views.py
import numpy as np
from django.shortcuts import render
from .forms import InterestForm, BankForm, TaxForm
import pandas as pd
import plotly.express as px
import plotly.graph_objs as go
from .models import Bank
from .calculator import Calculator
from .plot import Plot

def home_view(request):

    return render(request, "home.html", {})

def tax_view(request):
    tax_form = TaxForm(request.POST or None)
    if request.method == "POST":
        thuebutton = request.POST.get("thuephi")
        thue_thu_nhap = ""
        phi_table = []

        if request.POST.get("form_type") == "thuephi":
            if tax_form.is_valid():
                gia_chuyen_nhuong = tax_form.cleaned_data.get("gia_chuyen_nhuong")
                thue_thu_nhap, df = Calculator.thue_phi_nha_dat(gia_chuyen_nhuong)
                phi_table = df.to_html(table_id="phi_table")

        context = {
            'tax_form': tax_form,
            'thuebutton': thuebutton,
            'phi_table': phi_table,
            'thue_thu_nhap': thue_thu_nhap
        }
    else:
        context = {
            'tax_form': tax_form,
        }

    return render(request, "interest/thue.html", context)

def bank_view(request):
    bank_form = BankForm(request.POST or None)
    if request.method == "POST":
        if bank_form.is_valid():
            lai_suat_NH = bank_form.cleaned_data.get("ten_ngan_hang")

        if request.POST.get("form_type") == "sosanh":
            sosanhbutton = request.POST.get("sosanh")
            bank = Bank.objects.all()
            fig = Plot.plot_lai_suat(bank)
            chart = fig.to_html()

            bank_list = Bank.objects.values_list('ten_ngan_hang', 'lai_suat').order_by('lai_suat')

        context = {
            'bank_form': bank_form,
            "sosanhbutton": sosanhbutton,
            'chart': chart,
            'lai_suat_NH': lai_suat_NH,
            'min_ten_NH': bank_list.first()[0],
            'min_lai': bank_list.first()[1],
            'max_ten_NH': bank_list.last()[0],
            'max_lai': bank_list.last()[1],
        }
    else:
        context = {
            'bank_form': bank_form,
        }

    return render(request, "interest/tracuu.html", context)

def interest_view(request):

    form = InterestForm(request.POST or None)
    if request.method == "POST":
        so_tien_vay = ""
        ky_han = ""
        lai_suat = ""
        table_data = []
        summary_table = []
        submitbutton = request.POST.get("laisuat")
        if request.POST.get("form_type") == "laisuat":
            if form.is_valid():
                so_tien_vay = form.cleaned_data.get("so_tien_vay")
                ky_han = form.cleaned_data.get("ky_han")
                lai_suat = form.cleaned_data.get("lai_suat")
                loai_hinh = form.cleaned_data.get("loai_hinh")
                if (loai_hinh == '1'):
                    df, df_style, summary_df = Calculator.ky_khoan_giam_dan(so_tien_vay, ky_han, lai_suat)
                    table_data = df_style.to_html(table_id="table_example")
                    summary_table = summary_df.to_html(table_id="summary_table")

                elif (loai_hinh == '2'):
                    df, df_style, summary_df = Calculator.ky_khoan_co_dinh(so_tien_vay, ky_han, lai_suat)
                    table_data = df_style.to_html(table_id="table_example")
                    summary_table = summary_df.to_html(table_id="summary_table")

                von = list(np.cumsum(df['Vốn phải trả<br>VND']))
                lai = list(np.cumsum(df['Lãi phải trả<br>VND']))
                fig_2 = Plot.plot_tich_luy(von, lai, df['Dư nợ đầu kỳ<br>VND'], df['Số kỳ trả'])
                chart_2 = fig_2.to_html()

                fig_1 = Plot.plot_vonlai_theoky(df['Vốn phải trả<br>VND'], df['Lãi phải trả<br>VND'],
                                                df['Số kỳ trả'])
                chart_1 = fig_1.to_html()

        context = {
            "form": form,
            "so_tien_vay": so_tien_vay,
            "ky_han": ky_han,
            "submitbutton": submitbutton,
            "lai_suat": lai_suat,
            'table_data': table_data,
            'summary_table': summary_table,
            'chart_2': chart_2,
            'chart_1': chart_1,
        }
    else:
        context = {
            'form': form,
        }

    return render(request, "interest/laisuat.html", context)

real_estate_project/interestapp/templates/interest/laisuat.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'detail.css' %}">
    <script src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-2c7831bb44f98c1391d6a4ffda0e1fd302503391ca806e7fcc7b9b87197aec26.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
     <script id="rendered-js">
        function updateTextView(_obj){
            var num = getNumber(_obj.val());
            if(num==0){
                _obj.val('');
            }else{
            _obj.val(num.toLocaleString());
            }
        }
        function getNumber(_str){
            var arr = _str.split('');
            var out = new Array();
            for(var cnt=0;cnt<arr.length;cnt++){
                if(isNaN(arr[cnt])==false){
                    out.push(arr[cnt]);
                }
            }
        return Number(out.join(''));
        }
        $(document).ready(function(){
            $('input[id=id_so_tien_vay]').on('keyup',function(){
            updateTextView($(this));
        });
       });
     </script>

    <h3> Tính lãi suất cần trả</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="form_type" value="laisuat">
        <p colspan="2" style="text-align:center"><input type="Submit" name="laisuat" value="Xem kết quả"/></p>
    </form>
    {% if submitbutton == "Xem kết quả" %}
        {{ chart_1|safe }}
        {{ chart_2|safe }}
    <!-- DataTable content -->
    <div class="summary-body">
        {{ summary_table | safe }}
    </div>
    <div class="card-body">
        {{ table_data | safe }}
    </div>

    <!-- datatables JS -->
    <script type="text/javascript"src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript"src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>
    <script>
        {% comment %} Initialize DataTable {% endcomment %}
        $(document).ready(function() {
            $('#table_example').DataTable();
        } );
        $(document).ready(function() {
            $('#summary_table').DataTable();
        } );
    </script>
    {% endif %}

{% endblock %}

real_estate_project/interestapp/templates/interest/thue.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'detail.css' %}">
    <script src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-2c7831bb44f98c1391d6a4ffda0e1fd302503391ca806e7fcc7b9b87197aec26.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
     <script id="rendered-js">
        function updateTextView(_obj){
            var num = getNumber(_obj.val());
            if(num==0){
                _obj.val('');
            }else{
            _obj.val(num.toLocaleString());
            }
        }
        function getNumber(_str){
            var arr = _str.split('');
            var out = new Array();
            for(var cnt=0;cnt<arr.length;cnt++){
                if(isNaN(arr[cnt])==false){
                    out.push(arr[cnt]);
                }
            }
        return Number(out.join(''));
        }

        $(document).ready(function(){
            $('input[id=id_gia_chuyen_nhuong]').on('keyup',function(){
            updateTextView($(this));
        });
       });

        $(document).ready(function(){
            $('input[id=id_gia_dat]').on('keyup',function(){
            updateTextView($(this));
        });
       });

       $(document).ready(function(){
            $('input[id=id_dien_tich]').on('keyup',function(){
            updateTextView($(this));
        });
       });
     </script>

    <h3>Thuế phí khi mua bán nhà đất</h3>

    <form action="" method="POST">
        {% csrf_token %}
        {{ tax_form.as_p }}

        <input type="hidden" name="form_type" value="thuephi">
        <p style="text-align:center"><input type="Submit" name="thuephi" value="Tính thuế và phí"/></p>
    </form>
        {% if thuebutton == "Tính thuế và phí" %}
            <div class="summary-body" style="margin-top: 30px">
                <p style="height: 20px; text-align:left;">Thuế thu nhập cá nhân: <span style="font-size: 16px; color: green">{{thue_thu_nhap}}</span> VND</p>
            </div>
            <div class="summary-body">
            {{ phi_table | safe }}
            </div>
            <ul style="margin-top: 40px, font-family: Quicksand; font-size: 12px;">
                <li>Thuế thu nhập cá nhân = Giá chuyển nhượng x 2%</li>
                <li>Lệ phí trước bạ = Giá tính lệ phí trước bạ x 0.5%
                    <br>
                    Thông thường được tính bằng 0,5% x Tổng số tiền trong hợp đồng.
                </li>
                <li>Lệ phí thẩm định 0,15% giá trị chuyển nhượng (tối thiểu 100.000 đồng, tối đa 5.000.000 đồng).</li>
                <li>Lệ phí công chứng, được xác định theo giá trị tài sản hoặc giá trị hợp đồng, giao dịch được quy định
                    <br>
                    chi tiết tại Khoản 1, Điều 3 Thông tư liên tịch 62/2013/TTLT-BTC-BTP ngày 13-05-2013.
                </li>
                <li>Lệ phí địa chính 15.000 đồng</li>
                <li>Tham khảo thêm:
                    <a href="https://thuvienphapluat.vn/chinh-sach-phap-luat-moi/vn/thoi-su-phap-luat/bat-dong-san/40968/tong-hop-cac-loai-thue-phi-le-phi-phai-chiu-khi-mua-ban-nha-dat">
                        Tổng hợp các loại thuế, phí, lệ phí khi mua bán nhà đất
                    </a></li>
            </ul>
            <script type="text/javascript"src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
            <script type="text/javascript"src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>
            <script>
                {% comment %} Initialize DataTable {% endcomment %}
                $(document).ready(function() {
                    $('#phi_table').DataTable();
                } );
    </script>
        {% endif %}

{% endblock %}

real_estate_project/interestapp/templates/interest/tracuu.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'detail.css' %}">
    <h3> Tra cứu lãi suất ngân hàng</h3>

    <form action="" method="POST">
        {% csrf_token %}
        {{ bank_form.as_p }}

        <div class="showlaisuat">
            <div class="column">Lãi suất:</div>
            <div class="column" style="font-size: 16px; color:green;" id="id_lai_suat" >
                {% if sosanhbutton == "So sánh lãi suất"%}
                    {{ lai_suat_NH|safe }} %
                {% endif %}
            </div>
            <script>
                function show_laisuat() {
                    var x = document.getElementById("mySelect").value;
                    document.getElementById("id_lai_suat").innerHTML = x + " %";
            }
            </script>
        </div>
        <input type="hidden" name="form_type" value="sosanh">
        <p style="text-align:center; height:40px"><input type="Submit" name="sosanh" value="So sánh lãi suất"/></p>
        </form>
        {% if sosanhbutton == "So sánh lãi suất" %}
            {{ chart|safe }}
            <div style="margin-left: 40px">
                <p>Ngân hàng <span style="color:green">{{min_ten_NH|safe}}</span> có lãi suất cho vay <span style="color:green">thấp nhất {{min_lai|safe}} % </span></p>
                <p>Ngân hàng <span style="color:red">{{max_ten_NH|safe}}</span> có lãi suất cho vay <span style="color:red">cao nhất {{max_lai|safe}} % </span></p>
            </div>
        {% endif %}


{% endblock %}